### ISSUE TITLE
Get y axis correct on visualisation.

### ISSUE THREAD

**Issue by hawesie** [hawesie/rp14-exercise4#1]

**Comment by frebib** [comment]
There is one quick-fix that can be applied to this by transforming the Graphics2D object upside-down but it also flips the text. I suppose it is a small price to pay until someone has the time to fix it properly

> Insert into LineMapVisualisation.java @ line 141
> 
> ``` java
> int height = getHeight() / 2;
> g2.translate(0, height);
> g2.scale(1, -1);
> g2.translate(0, -height);
> ```

**Comment by hawesie** [comment]
If you make this into a pull request I will add it. Maybe add a flag in the constructor to enable/disable it.
